# Generated by Django 3.0.3 on 2025-04-03 20:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20250327_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartmen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('apartnen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accommodation')),
            ],
        ),
    ]
