# Generated by Django 3.0.3 on 2025-04-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_apartmen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmen',
            old_name='apartnen',
            new_name='apartmen',
        ),
    ]
