# Generated by Django 3.0.3 on 2025-04-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_apartmen'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmen',
            name='accommodation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Accommodation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmen',
            name='availability',
            field=models.PositiveIntegerField(default=None, verbose_name='количество свободных номеров'),
        ),
        migrations.AddField(
            model_name='apartmen',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='описание типа номеров'),
        ),
        migrations.AddField(
            model_name='apartmen',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='apartmen_img'),
        ),
        migrations.AddField(
            model_name='apartmen',
            name='name',
            field=models.CharField(default=0, max_length=128, unique=True, verbose_name='название типа номеров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartmen',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена % об базового тарифа'),
        ),
        migrations.AddField(
            model_name='apartmen',
            name='short_desc',
            field=models.TextField(blank=True, default=None, max_length=60, verbose_name='краткое описание типа номеров'),
        ),
    ]
