# Generated by Django 3.0.3 on 2025-04-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_partsofworld'),
    ]

    operations = [
        migrations.AddField(
            model_name='listofcountries',
            name='partsofworld',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.PartsOfWorld'),
        ),
    ]
