# Generated by Django 3.0.3 on 2025-04-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена бронирования'),
        ),
    ]
