# Generated by Django 3.0.3 on 2025-03-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20250328_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercaseprofile',
            name='param_id',
            field=models.UUIDField(verbose_name='id параметра профиля'),
        ),
    ]
