# Generated by Django 3.0.3 on 2025-04-04 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0004_basket_apartmen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='apartmen',
        ),
    ]
